[window]
# opacity = 0.95
# decorations = "Full"
decorations = "none"
# decorations_theme_variant = "Dark"

# [window.padding]
# x = 12 
# y = 12 

[font]
size = 13.0

# JetBrainsMono / Iosevka Nerd Font
[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Regular"

[font.italic]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Regular"


[colors.primary]
background = "#212122"
foreground = "#cdd6f4"

# [colors.cursor]
# text = "#000000"
# cursor = "#ffffff"
#
# [colors.selection]
# text = "CellForeground"
# background = "#44475a"
#
# [colors.normal]
# black   = "#1e1e2e"
# red     = "#f38ba8"
# green   = "#a6e3a1"
# yellow  = "#f9e2af"
# blue    = "#89b4fa"
# magenta = "#f5c2e7"
# cyan    = "#94e2d5"
# white   = "#bac2de"
#
# [colors.bright]
# black   = "#45475a"
# red     = "#f38ba8"
# green   = "#a6e3a1"
# yellow  = "#f9e2af"
# blue    = "#89b4fa"
# magenta = "#f5c2e7"
# cyan    = "#94e2d5"
# white   = "#cdd6f4"

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
	# { key = "V", mods = "Control|Shift", action = "Paste" },
	# { key = "C", mods = "Control|Shift", action = "Copy" },
	# { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[env]
TERM = "xterm-256color"

